[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
package = "netlify-plugin-ghost-markdown"
  [plugins.inputs]

  ghostURL = "https://outbound-project.ghost.io"
  ghostKey = "${CONTENT_API_KEY}"